version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN:?err}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - VERSION=docker
    volumes:
      - ./apps/plex/config:/config
      - ${MEDIA_DIRECTORY_1:?err}:${MEDIA_DIRECTORY_1:?err}
      - ${MEDIA_DIRECTORY_2}:${MEDIA_DIRECTORY_2}
      - ${MEDIA_DIRECTORY_3}:${MEDIA_DIRECTORY_3}
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - TZ=${TIMEZONE:-America/Winnipeg}
    volumes:
      - ./apps/radarr/config:/config
      - ${MEDIA_DIRECTORY_1:?err}:${MEDIA_DIRECTORY_1:?err}
      - ${MEDIA_DIRECTORY_2}:${MEDIA_DIRECTORY_2}
      - ${MEDIA_DIRECTORY_3}:${MEDIA_DIRECTORY_3}
    ports:
      - ${RADARR_PORT:-7878}:7878
    restart: always

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - TZ=${TIMEZONE:-America/Winnipeg}
    volumes:
      - ./apps/sonarr/config:/config
      - ${MEDIA_DIRECTORY_1:?err}:${MEDIA_DIRECTORY_1:?err}
      - ${MEDIA_DIRECTORY_2}:${MEDIA_DIRECTORY_2}
      - ${MEDIA_DIRECTORY_3}:${MEDIA_DIRECTORY_3}
    ports:
      - ${SONARR_PORT:-8989}:8989
    links:
      - plex
      - qbittorrentvpn
    restart: always

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - TZ=${TIMEZONE:-America/Winnipeg}
    volumes:
      - ./apps/prowlarr/config:/config
      - ${MEDIA_DIRECTORY_1:?err}:${MEDIA_DIRECTORY_1:?err}
      - ${MEDIA_DIRECTORY_2}:${MEDIA_DIRECTORY_2}
      - ${MEDIA_DIRECTORY_3}:${MEDIA_DIRECTORY_3}
    ports:
      - ${PROWLARR_PORT:-9696}:9696
    links:
      - flaresolverr
      - radarr
      - sonarr
      - plex
      - qbittorrentvpn
    restart: always

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TIMEZONE:-America/Winnipeg}
    restart: always 
